CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;

CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.TARGET_DWH;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.DATA_MARTS;

CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.RAW_DATA.MY_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS AIRLINE_DWH.RAW_DATA.MY_INTERNAL_STAGE
    FILE_FORMAT = AIRLINE_DWH.RAW_DATA.MY_CSV_FORMAT;