TRUNCATE TABLE AIRLINE_DWH.RAW_DATA.AIRLINE_RAW_TABLE;

COPY INTO AIRLINE_DWH.RAW_DATA.AIRLINE_RAW_TABLE
FROM @AIRLINE_DWH.RAW_DATA.MY_INTERNAL_STAGE
PATTERN = '.*Airline.*'
FILE_FORMAT = (FORMAT_NAME = 'AIRLINE_DWH.RAW_DATA.MY_CSV_FORMAT')
ON_ERROR = 'CONTINUE'
FORCE = TRUE;