CREATE TABLE IF NOT EXISTS AIRLINE_DWH.TARGET_DWH.DIM_PASSENGER (
    PASSENGER_SK STRING, 
    PASSENGER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    GENDER STRING,
    NATIONALITY STRING,
    -- 
    VALID_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AIRLINE_DWH.TARGET_DWH.DIM_AIRPORT (
    AIRPORT_SK STRING DEFAULT UUID_STRING(),
    AIRPORT_NAME STRING,
    AIRPORT_COUNTRY_CODE STRING,
    COUNTRY_NAME STRING,
    AIRPORT_CONTINENT STRING,
    CONTINENT_NAME STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AIRLINE_DWH.TARGET_DWH.FACT_FLIGHTS (
    FLIGHT_ID STRING DEFAULT UUID_STRING(),
    PASSENGER_SK STRING,
    AIRPORT_SK STRING,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT_CODE STRING,
    PILOT_NAME STRING,
    FLIGHT_STATUS STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);