CREATE OR REPLACE TEMPORARY TABLE TEMP_PREPPED_DATA AS
SELECT DISTINCT
    TRIM(PASSENGER_ID) AS PASSENGER_ID,
    TRIM(AIRPORT_NAME) AS AIRPORT_NAME,
    TRIM(AIRPORT_COUNTRY_CODE) AS AIRPORT_COUNTRY_CODE,
    TRIM(COUNTRY_NAME) AS COUNTRY_NAME,                
    TRIM(AIRPORT_CONTINENT) AS AIRPORT_CONTINENT,      
    TRIM(CONTINENTS) AS CONTINENT_NAME,
    TRIM(FIRST_NAME) AS FIRST_NAME,
    TRIM(LAST_NAME) AS LAST_NAME,
    GENDER,
    TRIM(NATIONALITY) AS NATIONALITY,
    TRY_TO_DATE(DEPARTURE_DATE, 'MM/DD/YYYY') AS CLEAN_DEPARTURE_DATE,
    ARRIVAL_AIRPORT,
    PILOT_NAME,
    FLIGHT_STATUS
FROM AIRLINE_DWH.RAW_DATA.AIRLINE_RAW_TABLE
WHERE PASSENGER_ID IS NOT NULL 
  AND AIRPORT_NAME IS NOT NULL;

MERGE INTO AIRLINE_DWH.TARGET_DWH.DIM_PASSENGER AS target
USING (SELECT DISTINCT PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, NATIONALITY FROM TEMP_PREPPED_DATA) AS source
ON target.PASSENGER_ID = source.PASSENGER_ID AND target.IS_CURRENT = TRUE
WHEN MATCHED AND (target.FIRST_NAME != source.FIRST_NAME OR target.LAST_NAME != source.LAST_NAME) THEN
    UPDATE SET target.VALID_TO = CURRENT_TIMESTAMP(), target.IS_CURRENT = FALSE;

INSERT INTO AIRLINE_DWH.TARGET_DWH.DIM_PASSENGER (
    PASSENGER_SK, PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, NATIONALITY, VALID_FROM, IS_CURRENT
)
SELECT UUID_STRING(), PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, NATIONALITY, CURRENT_TIMESTAMP(), TRUE
FROM TEMP_PREPPED_DATA source
WHERE NOT EXISTS (SELECT 1 FROM AIRLINE_DWH.TARGET_DWH.DIM_PASSENGER t WHERE t.PASSENGER_ID = source.PASSENGER_ID AND t.IS_CURRENT = TRUE)
GROUP BY PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, NATIONALITY;

INSERT INTO AIRLINE_DWH.TARGET_DWH.DIM_AIRPORT (
    AIRPORT_SK, 
    AIRPORT_NAME, 
    AIRPORT_COUNTRY_CODE, 
    COUNTRY_NAME, 
    AIRPORT_CONTINENT, 
    CONTINENT_NAME
)
SELECT 
    UUID_STRING(), 
    AIRPORT_NAME, 
    MAX(AIRPORT_COUNTRY_CODE),
    MAX(COUNTRY_NAME), 
    MAX(AIRPORT_CONTINENT), 
    MAX(CONTINENT_NAME)
FROM TEMP_PREPPED_DATA
WHERE AIRPORT_NAME NOT IN (SELECT AIRPORT_NAME FROM AIRLINE_DWH.TARGET_DWH.DIM_AIRPORT)
GROUP BY AIRPORT_NAME;

INSERT INTO AIRLINE_DWH.TARGET_DWH.FACT_FLIGHTS (
    PASSENGER_SK, AIRPORT_SK, DEPARTURE_DATE, ARRIVAL_AIRPORT_CODE, PILOT_NAME, FLIGHT_STATUS
)
SELECT 
    dp.PASSENGER_SK,
    da.AIRPORT_SK,
    raw.CLEAN_DEPARTURE_DATE,
    raw.ARRIVAL_AIRPORT,
    raw.PILOT_NAME,
    raw.FLIGHT_STATUS
FROM TEMP_PREPPED_DATA raw
JOIN AIRLINE_DWH.TARGET_DWH.DIM_PASSENGER dp 
  ON raw.PASSENGER_ID = dp.PASSENGER_ID AND dp.IS_CURRENT = TRUE
JOIN AIRLINE_DWH.TARGET_DWH.DIM_AIRPORT da 
  ON raw.AIRPORT_NAME = da.AIRPORT_NAME;