CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.DATA_MARTS.VW_AIRPORT_PERFORMANCE AS
SELECT 
    A.AIRPORT_NAME, 
    A.COUNTRY_NAME, 
    A.CONTINENT_NAME, 
    COUNT(F.FLIGHT_ID) AS TOTAL_FLIGHTS, 
    COUNT(DISTINCT F.PASSENGER_SK) AS UNIQUE_PASSENGERS
FROM AIRLINE_DWH.TARGET_DWH.FACT_FLIGHTS F 
JOIN AIRLINE_DWH.TARGET_DWH.DIM_AIRPORT A ON F.AIRPORT_SK = A.AIRPORT_SK
GROUP BY A.AIRPORT_NAME, A.COUNTRY_NAME, A.CONTINENT_NAME
ORDER BY TOTAL_FLIGHTS DESC;

CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.DATA_MARTS.VW_PASSENGER_PROFILE AS
SELECT 
    P.NATIONALITY, 
    P.GENDER, 
    COUNT(F.FLIGHT_ID) AS FLIGHTS_COUNT
FROM AIRLINE_DWH.TARGET_DWH.FACT_FLIGHTS F 
JOIN AIRLINE_DWH.TARGET_DWH.DIM_PASSENGER P ON F.PASSENGER_SK = P.PASSENGER_SK
GROUP BY P.NATIONALITY, P.GENDER 
ORDER BY FLIGHTS_COUNT DESC;

CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.DATA_MARTS.VW_DAILY_FLIGHTS AS
SELECT 
    F.DEPARTURE_DATE, 
    A.COUNTRY_NAME AS DEPARTURE_COUNTRY, 
    COUNT(F.FLIGHT_ID) AS TOTAL_FLIGHTS
FROM AIRLINE_DWH.TARGET_DWH.FACT_FLIGHTS F 
JOIN AIRLINE_DWH.TARGET_DWH.DIM_AIRPORT A ON F.AIRPORT_SK = A.AIRPORT_SK
GROUP BY F.DEPARTURE_DATE, A.COUNTRY_NAME
ORDER BY F.DEPARTURE_DATE DESC;